from typing import Any, List, Tuple
import numpy as np

def face_locations(img: Any, number_of_times_to_upsample: int = 1, model: str = "hog") -> List[Tuple[int, int, int, int]]: ...
def face_encodings(face_image: Any, known_face_locations: Any = None, num_jitters: int = 1, model: str = "small") -> List[np.ndarray]: ...
def compare_faces(known_face_encodings: List[np.ndarray], face_encoding_to_check: np.ndarray, tolerance: float = 0.6) -> List[bool]: ...
def face_distance(face_encodings: List[np.ndarray], face_to_compare: np.ndarray) -> np.ndarray: ...
