/**
 * India Hierarchical Location Data (State -> District -> Cities)
 * Comprehensive coverage for Kerala and major Indian States/Territories
 */

export const INDIA_LOCATION_DATA = {
  Kerala: {
    Ernakulam: [
      "Kochi",
      "Ernakulam",
      "Aluva",
      "Kakkanad",
      "Kalamassery",
      "Tripunithura",
      "Angamaly",
      "Perumbavoor",
      "Muvattupuzha",
      "Kothamangalam",
      "North Paravur",
      "Piravom",
    ],
    Thiruvananthapuram: [
      "Thiruvananthapuram",
      "Kazhakkoottam",
      "Neyyattinkara",
      "Attingal",
      "Varkala",
      "Nedumangad",
      "Parassala",
      "Kattakada",
    ],
    Kollam: [
      "Kollam",
      "Karunagappally",
      "Kottarakkara",
      "Punalur",
      "Paravur",
      "Pathanapuram",
      "Anchal",
      "Chavara",
    ],
    Pathanamthitta: [
      "Pathanamthitta",
      "Thiruvalla",
      "Adoor",
      "Ranni",
      "Pandalam",
      "Mallappally",
      "Konni",
    ],
    Alappuzha: [
      "Alappuzha",
      "Cherthala",
      "Kayamkulam",
      "Mavelikkara",
      "Haripad",
      "Chengannur",
      "Ambalappuzha",
    ],
    Kottayam: [
      "Kottayam",
      "Changanassery",
      "Pala",
      "Vaikom",
      "Kanjirappally",
      "Erattupetta",
      "Ettumanoor",
    ],
    Idukki: [
      "Thodupuzha",
      "Kattappana",
      "Munnar",
      "Adimali",
      "Nedumkandam",
      "Peerumade",
    ],
    Thrissur: [
      "Thrissur",
      "Guruvayur",
      "Chalakudy",
      "Kodungallur",
      "Kunnamkulam",
      "Irinjalakuda",
      "Wadakkanchery",
    ],
    Palakkad: [
      "Palakkad",
      "Ottapalam",
      "Shornur",
      "Chittur",
      "Mannarkkad",
      "Pattambi",
      "Alathur",
    ],
    Malappuram: [
      "Malappuram",
      "Manjeri",
      "Tirur",
      "Perinthalmanna",
      "Ponnani",
      "Kondotty",
      "Nilambur",
      "Kottakkal",
    ],
    Kozhikode: [
      "Kozhikode",
      "Vadakara",
      "Koyilandy",
      "Feroke",
      "Ramanattukara",
      "Koduvally",
      "Mukkam",
    ],
    Wayanad: [
      "Kalpetta",
      "Mananthavady",
      "Sulthan Bathery",
      "Vythiri",
      "Meppadi",
    ],
    Kannur: [
      "Kannur",
      "Thalassery",
      "Payyanur",
      "Mattannur",
      "Iritty",
      "Taliparamba",
      "Kuthuparamba",
    ],
    Kasaragod: [
      "Kasaragod",
      "Kanhangad",
      "Nileshwaram",
      "Uppala",
      "Cheruvathur",
      "Manjeshwaram",
    ],
  },
  "Tamil Nadu": {
    Chennai: [
      "Chennai Central",
      "T. Nagar",
      "Velachery",
      "Anna Nagar",
      "Adyar",
      "Tambaram",
      "Guindy",
    ],
    Coimbatore: [
      "Coimbatore City",
      "Pollachi",
      "Mettupalayam",
      "Udumalaipettai",
    ],
    Madurai: ["Madurai City", "Melur", "Thirumangalam"],
    Salem: ["Salem City", "Mettur", "Attur"],
    Tiruchirappalli: ["Tiruchirappalli", "Srirangam", "Lalgudi"],
  },
  Karnataka: {
    "Bengaluru Urban": [
      "Bengaluru City",
      "Whitefield",
      "Electronic City",
      "Indiranagar",
      "Yelahanka",
      "Marathahalli",
    ],
    Mysuru: ["Mysuru City", "Nanjangud", "Hunsur"],
    "Dakshina Kannada": ["Mangaluru", "Bantwal", "Puttur"],
    "Hubballi-Dharwad": ["Hubballi", "Dharwad"],
  },
  Maharashtra: {
    "Mumbai Suburban": [
      "Mumbai City",
      "Andheri",
      "Bandra",
      "Borivali",
      "Thane",
      "Navi Mumbai",
    ],
    Pune: ["Pune City", "Pimpri-Chinchwad", "Hinjewadi", "Baramati"],
    Nagpur: ["Nagpur City", "Kamptee"],
    Nashik: ["Nashik City", "Malegaon"],
  },
  Delhi: {
    "Central Delhi": ["Connaught Place", "Karol Bagh", "Paharganj"],
    "New Delhi": ["Chanakyapuri", "Vasant Kunj", "Connaught Place"],
    "South Delhi": ["Saket", "Hauz Khas", "Greater Kailash"],
    "North Delhi": ["Pitampura", "Civil Lines", "Rohini"],
  },
  Telangana: {
    Hyderabad: [
      "Hyderabad City",
      "Secunderabad",
      "Gachibowli",
      "Madhapur",
      "Hitech City",
    ],
    "Medchal-Malkajgiri": ["Kukatpally", "LB Nagar", "Malkajgiri"],
    Warangal: ["Warangal", "Hanamkonda"],
  },
  "Andhra Pradesh": {
    Visakhapatnam: ["Visakhapatnam City", "Gajuwaka", "Anakapalle"],
    NTR: ["Vijayawada", "Mangalagiri"],
    Guntur: ["Guntur City", "Tenali"],
  },
  Gujarat: {
    Ahmedabad: ["Ahmedabad City", "Gandhinagar", "Sanand"],
    Surat: ["Surat City", "Navsari"],
    Vadodara: ["Vadodara City"],
  },
  "West Bengal": {
    Kolkata: ["Kolkata City", "Salt Lake", "New Town", "Howrah"],
    Darjeeling: ["Siliguri", "Darjeeling Town"],
  },
};

export const STATES_LIST = Object.keys(INDIA_LOCATION_DATA);
